In [61]:
def read_csv(path):
    res = {}
    with open(path,"r") as f:
        head = f.readline().strip().split(",")
        for it in f.readlines():
            it = it.strip().split(",")
            if len(head) == len(it):
                for _h, _i in zip(head, it):
                    res[_h] = res.get(_h, [])
                    res[_h].append(_i)
            else:
                print("error")
    return res

In [1]:
import csv
import pandas as pd
train_data = pd.read_csv("pro_train.csv")
test_data = pd.read_csv("pro_test.csv")

In [63]:
# train_data = read_csv("pro_train.csv")


In [64]:
train_data.keys()

Index(['ID', 'Dependents', 'MonthlyCharges', 'Partner', 'PhoneService',
       'SeniorCitizen', 'TotalCharges', 'tenure', 'Label', 'Contract_One year',
       'Contract_Two year', 'InternetService_Fiber optic',
       'InternetService_No', 'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'gender_Male', 'DeviceProtection_No', 'DeviceProtection_Yes',
       'MultipleLines_No', 'MultipleLines_Yes', 'TVProgram_No',
       'TVProgram_Yes'],
      dtype='object')

In [65]:
train_data.describe()

ID   Dependents  MonthlyCharges      Partner  PhoneService  \
count  5227.000000  5227.000000     5227.000000  5227.000000   5227.000000   
mean   2613.000000     0.225368       66.823765     0.423379      0.929214   
std    1509.049259     0.417865       28.862749     0.494142      0.256492   
min       0.000000     0.000000       18.250000     0.000000      0.000000   
25%    1306.500000     0.000000       45.000000     0.000000      1.000000   
50%    2613.000000     0.000000       74.200000     0.000000      1.000000   
75%    3919.500000     0.000000       89.900000     1.000000      1.000000   
max    5226.000000     1.000000      118.600000     1.000000      1.000000   

       SeniorCitizen  TotalCharges       tenure        Label  \
count    5227.000000   5227.000000  5227.000000  5227.000000   
mean        0.118615   2084.477153    28.775971     0.372489   
std         0.323366   2183.825066    24.293077     0.483514   
min         0.000000     18.800000     0.000000     0.000000   
25%         0.000000    292.979609     5.000000     0.000000   
50%         0.000000   1218.650000    23.000000     0.000000   
75%         0.000000   3373.825000    51.000000     1.000000   
max         1.000000   8564.750000    72.000000     1.000000   

       Contract_One year      ...        \
count        5227.000000      ...         
mean            0.165870      ...         
std             0.371999      ...         
min             0.000000      ...         
25%             0.000000      ...         
50%             0.000000      ...         
75%             0.000000      ...         
max             1.000000      ...         

       PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
count                            5227.000000                     5227.000000   
mean                                0.163382                        0.481538   
std                                 0.369750                        0.499707   
min                                 0.000000                        0.000000   
25%                                 0.000000                        0.000000   
50%                                 0.000000                        0.000000   
75%                                 0.000000                        1.000000   
max                                 1.000000                        1.000000   

       PaymentMethod_Mailed check  gender_Male  DeviceProtection_No  \
count                 5227.000000  5227.000000          5227.000000   
mean                     0.188827     0.493017             0.531280   
std                      0.391409     0.499999             0.499068   
min                      0.000000     0.000000             0.000000   
25%                      0.000000     0.000000             0.000000   
50%                      0.000000     0.000000             1.000000   
75%                      0.000000     1.000000             1.000000   
max                      1.000000     1.000000             1.000000   

       DeviceProtection_Yes  MultipleLines_No  MultipleLines_Yes  \
count           5227.000000       5227.000000        5227.000000   
mean               0.287737          0.486321           0.442893   
std                0.452751          0.499861           0.496776   
min                0.000000          0.000000           0.000000   
25%                0.000000          0.000000           0.000000   
50%                0.000000          0.000000           0.000000   
75%                1.000000          1.000000           1.000000   
max                1.000000          1.000000           1.000000   

       TVProgram_No  TVProgram_Yes  
count   5227.000000    5227.000000  
mean       0.438492       0.380524  
std        0.496250       0.485562  
min        0.000000       0.000000  
25%        0.000000       0.000000  
50%        0.000000       0.000000  
75%        1.000000       1.000000  
max        1.000000       1.000000  

[8 rows x 23 columns]

In [4]:
train_y = train_data["Label"].values
train_x = train_data.drop(["ID","Label"],axis = 1)[:].values
test_x = test_data.drop(["ID"],axis = 1).values

In [3]:
import xlrd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn import metrics



In [68]:
print(type(train_y))
print(train_y)
print(type(train_x))
print(train_x[:5])
print(len(train_x),len(train_y))

<class 'numpy.ndarray'>
[0 1 0 ... 0 0 1]
<class 'numpy.ndarray'>
[[0.00000000e+00 2.41500000e+01 1.00000000e+00 1.00000000e+00
  0.00000000e+00 1.50590000e+03 6.00000000e+01 1.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 7.61422838e+01 0.00000000e+00 1.00000000e+00
  0.00000000e+00 9.46581518e+02 1.20000000e+01 0.00000000e+00
  0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
  0.00000000e+00]
 [1.00000000e+00 2.62000000e+01 1.00000000e+00 1.00000000e+00
  0.00000000e+00 1.07750000e+03 4.00000000e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+0

In [5]:
# dev_x = train_x[-100:]
# dev_y = train_y[-100:]
# train_x = train_x[:-100]
# train_y = train_y[:-100]
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.fit_transform(test_x)

In [6]:
log_model = LogisticRegression()

In [7]:
log_model.fit(train_x, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [84]:
test_x = test_data.drop(["ID"],axis = 1)[:].values

In [85]:
y_pred = log_model.predict(train_x)

In [86]:
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [8]:
y_pred = log_model.predict(test_x)
# print(metrics.confusion_matrix(dev_y, y_pred))
# print(metrics.classification_report(dev_y, y_pred))
# print(metrics.f1_score(dev_y, y_pred,average='macro'))

In [88]:
y_pred = log_model.predict(train_x)
print(metrics.confusion_matrix(train_y, y_pred))
print(metrics.classification_report(train_y, y_pred))
print(metrics.f1_score(train_y, y_pred,average='macro'))

[[2446  645]
 [ 522 1314]]
             precision    recall  f1-score   support

          0       0.82      0.79      0.81      3091
          1       0.67      0.72      0.69      1836

avg / total       0.77      0.76      0.76      4927

0.7499420389881579


In [77]:
print(metrics.confusion_matrix(train_y, y_pred))
print(metrics.classification_report(train_y, y_pred))

[[2567  651]
 [ 544 1365]]
             precision    recall  f1-score   support

          0       0.83      0.80      0.81      3218
          1       0.68      0.72      0.70      1909

avg / total       0.77      0.77      0.77      5127



In [18]:
import json
with open("LR_pre.csv","w") as f:
    csv_writer = csv.writer(f)
    csv_writer.writerow(["ID","Label"])
    for ID,Label in zip(test_data["ID"],y_pred):
        print(ID)
        if Label ==0:
            csv_writer.writerow([ID,"No"])
        else:
            csv_writer.writerow([ID,"Yes"])

5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
5351
5352
5353
5354
5355
5356
5357
5358
5359
5360
5361
5362
5363
5364
5365
5366
5367
5368
5369
5370
5371
5372
5373
5374
5375
5376
5377
5378
5379
5380
5381
5382
5383
5384
5385
5386
5387
5388
5389
5390
5391
5392
5393
5394
5395
5396
5397
5398
5399
5400
5401
5402
5403
5404
5405
5406
5407
5408
5409
5410
5411
5412
5413
5414
5415
5416
5417
5418
5419
5420
5421
5422
5423
5424
5425
5426


In [16]:
test_data["ID"]

0       5227
1       5228
2       5229
3       5230
4       5231
5       5232
6       5233
7       5234
8       5235
9       5236
10      5237
11      5238
12      5239
13      5240
14      5241
15      5242
16      5243
17      5244
18      5245
19      5246
20      5247
21      5248
22      5249
23      5250
24      5251
25      5252
26      5253
27      5254
28      5255
29      5256
        ... 
1277    6504
1278    6505
1279    6506
1280    6507
1281    6508
1282    6509
1283    6510
1284    6511
1285    6512
1286    6513
1287    6514
1288    6515
1289    6516
1290    6517
1291    6518
1292    6519
1293    6520
1294    6521
1295    6522
1296    6523
1297    6524
1298    6525
1299    6526
1300    6527
1301    6528
1302    6529
1303    6530
1304    6531
1305    6532
1306    6533
Name: ID, Length: 1307, dtype: int64